In [1]:
import os
import pandas
import openpyxl
from walkdir import filtered_walk, dir_paths, all_paths, file_paths

import xlrd
from urlparse import urlparse
from openpyxl import Workbook

import dominate
from dominate.tags import *

import ntpath

import operator

from docx import Document

import mammoth

Find all the excel files in this folder.

Cycle through other folder - word/powerpoint/pdf/js.

What file types are in each folder? xls/pdf/js/pptx.
Find the file type, then search for it.

In [2]:
assefol = ('/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/')

In [3]:
assefol

'/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/'

In [4]:
asselis = os.listdir(assefol)

In [5]:
for asse in asselis:
    print asse
    #allfil = file_paths(filtered_walk(exceldir, depth=100, included_files=['*.xls']))

file
image
js_file
excel_doc
pdf_file
word_doc
powerpoint_doc

In [121]:
exceldir = ('/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/')

In [122]:
files = file_paths(filtered_walk(exceldir, depth=100, included_files=['*']))

In [123]:
docfiles = file_paths(filtered_walk(exceldir, depth=100, included_files=['*.doc']))

In [124]:
#for fil in files:
#    print fil[81:]

Cycles though every file found in folder. 
Sort each file into folders/dict

In [125]:
alfilext = []

In [126]:
allfiltype = []

In [127]:
dirtpy = dict()

In [128]:
for docf in docfiles:
    print docf

/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/163590/Continuity-of-Early-Learning-Learning-Progress-and-Outcomes-Overview-Report.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/163608/Continuity-of-Early-Learning-Case-Studies.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/107394/Annual-ECE-Summary-Report-2005.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/165435/QS-World-University-Subject-Rankings.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/144078/NZSCED-2000-Narrow-Field-Version-1.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/57939/Sec-Guide_2009-v1.3.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/147579/RS61H-Homebased-letter2014.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/121938/Kindergarten-2013.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/109617/2012-RS61P-Playcentre.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/101310/RS61P-Playcentre-2011-Letter.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/77172/RS61E-Casual-Education-and-Care-2010.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/9492/Kindergarten07.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/164958/RS61H-Homebased-Education-and-Care-Annual-Return-2015.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/109635/2012-RS61P-Licensed-Playcentres-Annual-Return.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/46986/RS61CS---The-Correspondence-School-at-1-July-2009.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/81159/NEW-954_KWA-English.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/55563/09-07-28-Te-piko-o-te-mahuri2.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/80772/955a_Te-Kotahitanga-Summary_htmlversion.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/7098/hui-taumata-web-word.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/49191/Samoan-QTRD-Exec-summary-final.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/77091/951_TELA-Auckland.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/74535/942_TchrReview-05052010.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0006/91437/970_Implementation-Exploratory.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/163601/Continuity-of-Early-Learning-Literature-Scan.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/103517/SSMC-Minutes-2004.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/8054/Knowledge-Building-Strategy.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/26243/EnglishSurvey.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/7217/language-codes.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/162035/2014-Decile-Review-Survey_SAM.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/7271/Circular-199848-retyped.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/13742/Sec_Guide_2008_v1.1.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/7262/School-Leavers-Users-Guide-v0-1.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/101294/RS61K-Kindergartens-at-1-July-2011.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/10457/RS61K_-_Kindergartens_at_1_July_2007.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/11645/RS61LE-AR-Children-Playgroups-June2007.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/9512/RS61P-ARoCS-Licensed-Playcentres-1July06.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/114821/Evaluation-of-Literacy-and-Maths-Additional-Learning-Programmes-for-Students-2011.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/164150/2012-Special-Education-Clicent-Satistifaction-Survey.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/16181/841_Physical_Disabilities_noappendices.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/140336/Maori-Medium-Kaiako-Survey.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/144116/Whanau-Advisory-Group-Research-Project.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/9314/Economic-Outcomes-for-Maori-from-Tertiary-Education.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/15119/evaluation-report-on-the-implementation-of-the-cod.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/91223/E-LearningProvisionParticipation-25052011.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0017/101087/Factors-Linked-to-Young-Adult-Literacy.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/143740/Subject-Codes-2015.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/105049/ECESMC-Minutes-2004.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/26245/KoreanSurvey.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/15094/appendix-a.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/109720/eTAP-Instructions-2013.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/7273/Circular-200301-retyped.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/7264/Stand-downs-Users-Guide.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/121933/Barnardos-Education-and-Care-2013.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/109621/2012-RS61E-Guidelines-Barnardos-Education-and-Care.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/109630/2012-RS61H-Guidelines-Homebased.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/24931/RS61E_-_Education_and_Care_services_at_1_Jul_2008_-_final.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/10459/RS61E_-_Education_and_Care_services_at_1_Jul_2007.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/101359/976_NS-SSMEP2010.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/90730/966_OECD-report.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/104491/Orientation-and-Mobility-Review-for-publication.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/16183/841_Physical_Disabilities_AppendixA-v2.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/101377/974_NWRM.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/14365/Home_School_Partnership_Literacy_2007.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/56251/Literacy-and-Life-Skills-for-Maori-Adults-Further-Investigation.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0019/23815/Education-Work-and-Literacy.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/115639/Annual-ECE-Summary-Report-2012-7.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/102310/RT-Literacy-2014-Instr.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/144079/NZSCED-2000-Detailed-Field-Version-1.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/70387/Prim-Guide_2010-v1.1.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/147580/RS61E-Casual-Education-and-Care-services-2014-letter.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/121939/Playcentre-letter-2013.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/109618/2012-RS61K-Guidelines.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/77173/RS61E-Education-and-Care-services-2010.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/47626/Barnardos-Education-and-Care-2009.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/9493/Correspondence_School07.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/162691/Profile-Codebook-Jan-15.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/46987/RS61E---Education-and-Care-services-at-1-Jul-2009---final.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/148525/ECE-Participation-Programme-Evaluation-Delivery-of-ECE-Participation-Initiatives.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/81358/EAG-2010-NZ-report-09092010e.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/163618/Its-who-we-are-PB4L-School-wide-Studies.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/164149/2011-Special-Education-Clicent-Satistifaction-Survey.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/6955/831_Bilingual.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/55564/09-07-02-Learning-Foundations-for-Maori-Adults2.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/58129/NZ-Alumni-Survey-Report_Oct-2009-FINAL.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/57823/930_CIESs.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/142927/Resource-Teachers-Literacy-Operational-and-Policy-Review.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0007/54952/Literacy-and-Life-Skills-for-Pasifika-Adults.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/103390/Annual-ECE-Summary-Report-2011_final.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/103516/SSMC-Minutes-2005.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/16207/Pacific-Circle-Consortium.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/26242/ChineseSurvey.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/161341/NZSCED-Version-2-Detailed-Field.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/162034/2014-Decile-Review-Survey_MAO.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/13741/Prim_Guide_2008_v1-1.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/121930/RS61H-Homebased-Education-and-Care-Annual-Return-2013.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/101293/RS61H-Home-based-services-at-1-Jul-2011.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/9511/RS61LE-ARoC-Licence-exempt-Groups-June06.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/7702/bes-professional-development.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/127051/ECE-Participation-Programme-Evaluation.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/42271/Evaluation-of-the-ECE-ICT-Professional-Learning-Programme-Summary-Report.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/115180/Evaluative-Study-of-Co-located-Schools-Established-following-the-Christchurch-Earthquake.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/111085/National-Standards-School-Sample-Monitoring-and-Evaluation-Project-2011.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/21274/Maori_FactSheet_2004-06_Final.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/18700/Fact-Sheet-Pasifika-Peoples-in-Tertiary-Education-in-NZ-2006.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/15109/esol-survey-final-vol-1.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0016/91420/969_NLCEvaluation-Technical.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/107389/Annual-ECE-Summary-Report-2010-1.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/93718/EQI-Mailing-documents--Childrens-Address-Form.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/164962/RS61E-Casual-Education-and-Care-services-2015-letter.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/101305/RS61E-Barnardos-Education-and-Care-2011-Letter.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/77176/RS61P-Playcentre-2010.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/47629/Education-and-Care-services-2009.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/9487/Barnardos_Homebased07.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/77167/RS61E-Education-and-Care-services-at-1-Jul-2010-March-version.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/46990/RS61P---Playcentres-at-1-July-2009.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/163684/What-we-get-for-what-we-spend-Inputs-outputs-and-outcomes-of-Govts-tertiary-education-expenditure-2004-2013.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/91594/MASTER-DES-Report-10-10-12A.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/103789/983_NWRM-Te-Reo-Research.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/49186/QTRD-Maori-Med-Exec-Summary-final-a.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/163963/BackgroundPapers-MaoriMedium-FINAL2.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/78967/955_TK-Evaluation_V2-11082010.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/108001/Pasifika-Eduction-Research-Priorities-Using-research-to-realise-our-vision-for-Pasifika-learners.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/87328/Fact-Sheet-Pasifika-in-Tertiary-Education-in-NZ-2009.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/75898/944_TeuLeVa-30062010.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/19693/International_Student_Exchanges_Guidelines.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/76627/943_TELA-Otago-02062010.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/91675/968a_EvalNLC_Summary.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/76636/iCLT-Summary-final-draft-11082010.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/32131/FWWP_education_report_for_publication.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0010/101080/Literacy-Skills-of-Young-Adult-New-Zealanders.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0020/107390/Annual-ECE-Summary-Report-2009.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0020/152651/Application-Data-Sharing-Approval-2015-Company.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0020/8057/Collaborating-Across-Policy-2005.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0020/105563/Maori-Participation-and-Attainment-in-NCEA.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0020/15095/appendix-b-survey-english.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0020/7256/Board-of-Trustees-Users-Guide-v0.1.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0020/120917/RS61PG-Cover-letter-Playgroups.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0020/121934/Barnardos-Homebased-2013.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0020/47630/Homebased-2009.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0020/101765/RS61PG-Playgroups-2011.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0020/24932/RS61H_-_Home-based_services_at_1_Jul_2008_-_final.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0020/7706/bes-quality-teaching-early.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0020/111494/PFWInformationNeedsResearch19Sep2012.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0020/77141/946_TELA-Y1-3-15072010.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0003/107391/Annual-ECE-Summary-Report-2008.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0003/165432/Academic-Ranking-of-World-Universities.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0003/152652/Application-Data-Sharing-Approval-2015-Individual.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0003/15096/appendix-c-survey-chinese-and-other.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0003/93720/EQI-Mailing-documents--Confidentiality-Procedures.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0003/88482/2011-RR-Guides-Prim-Inter.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0003/7266/2007-roll-return-guidelines-primary-and-intermedia.doc
/media/removable/WILLIAMS30G/www.educationcounts.govt.nz/__data/assets/word_doc/0003/7275/prim-guide-2006-version-for-printing-2.doc

In [129]:
with open('/home/wcmckee/test.doc', 'rb') as docx_file:
    result = mammoth.convert_to_html(docx_file)
    print result.value # The generated HTML
        #messages = result.messages # Any messages, such as warnings during conversion

BadZipfile: File is not a zip file

In [ ]:
for f in files: 
    #print f
    fileName, fileExtension = os.path.splitext(f)
    #print fileName
    npach = ntpath.basename(fileName)
    dirtpy.update({npach : f})
    #print fileExtension
    alfilext.append(fileExtension)

In [ ]:
#x = {1: 2, 3: 4, 4: 3, 2: 1, 0: 0}
sorted_x = sorted(dirtpy.items(), key=operator.itemgetter(1))

Here are all file extensions in the __data folder.

In [ ]:
alfilb = set(alfilext)

In [ ]:
extdict = dict()

In [102]:
for alfi in alfilb:
    print alfi
    docfiles = file_paths(filtered_walk(exceldir, depth=100, included_files=['*' + alfi]))
    extdict.update({str(docfiles) : alfi})

.png
.docx
.JPG
.gif
.xlsx
.ppt
.pptx
.DOC
.css
.js
.GIF
.jpg
.xml
.doc
.xls
.pdf
.csv
.zip

In [103]:
#for exd in extdict.keys():
#    print exd
#    for ex in exd:
#        print ex
    #for ex in exd:
    #    print ex

In [132]:
exlfile = file_paths(filtered_walk(exceldir, depth=100, included_files=['*.xls']))

In [113]:
#pandexl = pandas.read_excel(exf)

In [ ]:
for exf in exlfile:
    #print exf
    opexf = open(exf, 'r')
    #rdex = xlrd.count_records(exf)
    #rdwk = xlrd.open_workbook(opexf)
    #print rdwk
    pandexl = pandas.read_excel(exf)
    #print pandexl.columns
    print pandexl.to_html()

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>This spreadsheet contains four worksheets:</th>
      <th>Unnamed: 1</th>
      <th>Unnamed: 2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0 </th>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>1 </th>
      <td>                                                 1</td>
      <td>                                   Read this first</td>
      <td> Provides information about the following three...</td>
    </tr>
    <tr>
      <th>2 </th>
      <td>                                                 2</td>
      <td>                                           Mergers</td>
      <td> Provides details about mergers taking effect a...</td>
    </tr>
    <tr>
      <th>3 </th>
      <td>                                                 3</td>
      <td>                                          Closures</td>
      <td>         Lists schools closed after 1 January 2007</td>
    </tr>
    <tr>
      <th>4 </th>
      <td>                                                 4</td>
      <td>                                       New Schools</td>
      <td>     Lists new schools opened after 1 January 2007</td>
    </tr>
    <tr>
      <th>5 </th>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>6 </th>
      <td> The information in this document is correct an...</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>7 </th>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>8 </th>
      <td> Please read the following comments for each wo...</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>9 </th>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>10</th>
      <td>                                           Mergers</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>11</th>
      <td>                                                 1</td>
      <td> For clarity and convenience, schools relating ...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>12</th>
      <td>                                                 2</td>
      <td> In the mergers that are due to a Network Revie...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>13</th>
      <td>                                                 3</td>
      <td> Where a school is NOT the continuing school, i...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>14</th>
      <td>                                                 4</td>
      <td> For the sake of administrative integrity, the ...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>15</th>
      <td>                                                 5</td>
      <td> Where a re-numbered continuing school has not ...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>16</th>
      <td>                                                 6</td>
      <td> In most situations the designated continuing s...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>17</th>
      <td>                                                 7</td>
      <td> Where there is a change of site, this is indic...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>18</th>
      <td>                                                 8</td>
      <td> In some Network Reviews one or more schools ha...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>19</th>
      <td>                                                 9</td>
      <td> To find out contact details (postal and locati...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>20</th>
      <td>                                               NaN</td>
      <td> http://www.minedu.govt.nz/index.cfm?layout=doc...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>21</th>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>22</th>
      <td>                                          Closures</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>23</th>
      <td>                                                 1</td>
      <td> Some closures are simple closures.  Some are d...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>24</th>
      <td>                                                 2</td>
      <td> Where a school has closed due to a merger, the...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>25</th>
      <td>                                                 3</td>
      <td> Where a re-numbered continuing school has not ...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>26</th>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>27</th>
      <td>                                       New Schools</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>28</th>
      <td>                                                 1</td>
      <td> Some new schools are simply brand-new schools....</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>29</th>
      <td>                                                 2</td>
      <td> Where a new school is the result of a merger, ...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>30</th>
      <td>                                                 3</td>
      <td> To find out contact details (postal and locati...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>31</th>
      <td>                                               NaN</td>
      <td> http://www.minedu.govt.nz/index.cfm?layout=doc...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>32</th>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>33</th>
      <td>                                    Any questions?</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>34</th>
      <td>                                               NaN</td>
      <td> Please contact Data Management Unit's Informat...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>35</th>
      <td>                                               NaN</td>
      <td>         mailto:information.officer@minedu.govt.nz</td>
      <td>                                               NaN</td>
    </tr>
  </tbody>
</table>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>This spreadsheet contains four worksheets:</th>
      <th>Unnamed: 1</th>
      <th>Unnamed: 2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0 </th>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>1 </th>
      <td>                                                 1</td>
      <td>                                   Read this first</td>
      <td> Provides information about the following three...</td>
    </tr>
    <tr>
      <th>2 </th>
      <td>                                                 2</td>
      <td>                                           Mergers</td>
      <td> Provides details about mergers taking effect b...</td>
    </tr>
    <tr>
      <th>3 </th>
      <td>                                                 3</td>
      <td>                                          Closures</td>
      <td> Lists schools closed between January 2006 and ...</td>
    </tr>
    <tr>
      <th>4 </th>
      <td>                                                 4</td>
      <td>                                       New Schools</td>
      <td> Lists new schools opened between January 2006 ...</td>
    </tr>
    <tr>
      <th>5 </th>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>6 </th>
      <td> The information in this document is correct an...</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>7 </th>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>8 </th>
      <td> Please read the following comments for each wo...</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>9 </th>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>10</th>
      <td>                                           Mergers</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>11</th>
      <td>                                                 1</td>
      <td> For clarity and convenience, schools relating ...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>12</th>
      <td>                                                 2</td>
      <td> In the mergers that are due to a Network Revie...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>13</th>
      <td>                                                 3</td>
      <td> Where a school is NOT the continuing school, i...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>14</th>
      <td>                                                 4</td>
      <td> For the sake of administrative integrity, the ...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>15</th>
      <td>                                                 5</td>
      <td> Where a re-numbered continuing school has not ...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>16</th>
      <td>                                                 6</td>
      <td> In most situations the designated continuing s...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>17</th>
      <td>                                                 7</td>
      <td> Where there is a change of site, this is indic...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>18</th>
      <td>                                                 8</td>
      <td> In some Network Reviews one or more schools ha...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>19</th>
      <td>                                                 9</td>
      <td> To find out contact details (postal and locati...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>20</th>
      <td>                                               NaN</td>
      <td> http://www.minedu.govt.nz/index.cfm?layout=doc...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>21</th>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>22</th>
      <td>                                          Closures</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>23</th>
      <td>                                                 1</td>
      <td> Some closures are simple closures.  Some are d...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>24</th>
      <td>                                                 2</td>
      <td> Where a school has closed due to a merger, the...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>25</th>
      <td>                                                 3</td>
      <td> Where a re-numbered continuing school has not ...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>26</th>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>27</th>
      <td>                                       New Schools</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>28</th>
      <td>                                                 1</td>
      <td> Some new schools are simply brand-new schools....</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>29</th>
      <td>                                                 2</td>
      <td> Where a new school is the result of a merger, ...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>30</th>
      <td>                                                 3</td>
      <td> To find out contact details (postal and locati...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>31</th>
      <td>                                               NaN</td>
      <td> http://www.minedu.govt.nz/index.cfm?layout=doc...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>32</th>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>33</th>
      <td>                                    Any questions?</td>
      <td>                                               NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>34</th>
      <td>                                               NaN</td>
      <td> Please contact Data Management Unit's Informat...</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>35</th>
      <td>                                               NaN</td>
      <td>         mailto:information.officer@minedu.govt.nz</td>
      <td>                                               NaN</td>
    </tr>
  </tbody>
</table>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Citizenship Codes 2007-- based on ISO-3166</th>
      <th>Unnamed: 1</th>
      <th>Unnamed: 2</th>
      <th>Unnamed: 3</th>
      <th>Unnamed: 4</th>
      <th>Unnamed: 5</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>NaN</th>
      <td>                      Mapping old code to new code</td>
      <td>                    NaN</td>
      <td>                                               NaN</td>
      <td>                                        NaN</td>
      <td> NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>NaN</th>
      <td> 2006: Previous version of country codes in use...</td>
      <td>                    NaN</td>
      <td>                                               NaN</td>
      <td>                                        NaN</td>
      <td> NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>NaN</th>
      <td> 2007: revised in 2006 for School Student Manag...</td>
      <td>                    NaN</td>
      <td>                                               NaN</td>
      <td>                                        NaN</td>
      <td> NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>NaN</th>
      <td>                                               NaN</td>
      <td> Key to Modified Codes:</td>
      <td>                                               NaN</td>
      <td>                                        NaN</td>
      <td> NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>NaN</th>
      <td>                                               NaN</td>
      <td>                      R</td>
      <td>      country not included in ISO-3166, so removed</td>
      <td>                                        NaN</td>
      <td> NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>NaN</th>
      <td>                                               NaN</td>
      <td>                      C</td>
      <td>                          country code has changed</td>
      <td>                                        NaN</td>
      <td> NaN</td>
      <td>                                               NaN</td>
    </tr>
    <tr>
      <th>NaN</th>
      <td>                                               NaN</td>

In [111]:
doc = dominate.document(title='educations-counts-data')

with doc.head:
    link(rel='stylesheet', href='style.css')
    script(type='text/javascript', src='script.js')

with doc:
    #with div(id='header').add(ol()):
        #for i in ['home', 'about', 'contact']:
            #li(a(i.title(), href='/%s.html' % i))

    with div(cls='row'):
        h1('education-counts-data')
        for exf in exlfile:
            #print exf
            opexf = open(exf, 'r')
            #rdex = xlrd.count_records(exf)
            #rdwk = xlrd.open_workbook(opexf)
            #print rdwk
            pandexl = pandas.read_excel(exf)
            #print pandexl.columns
            doc.add(pandexl.to_html())
    
        #for fil in files:
            #gied = afi.text
            #gifz = gied.replace(' ', '-')
            #giflow = gifz.lower()
            #a(dominate.tags.p(fil), href = fil)

#print doc

In [ ]:
for exf in exlfile:
    #print fil
    #opexl = open(fil, 'r')
    #opexl = xlrd.count_records(exf)
    #print opexl.read
    #print exshna()
    #print opexl
    
    opxa = xlrd.open_workbook(exf)
    #print opxa
    #print opxa.sheet_names()
    #print len(opxs.sheet_names()
    #fshet = opxa.sheet_names()[1]
    print opxa.nsheets
    print opxa.
    #print fshet
    
    #wshet = fshet.sheet_by_name(fshet)
    #nrows = wshet.nrows - 1
    #crow = -1
    
    #while crow < nrows:
    #    crow += 1
    #    row = wshet.row(crow)
    #    print row

In [ ]:
doc = dominate.document(title='educations-counts-data')

with doc.head:
    link(rel='stylesheet', href='style.css')
    script(type='text/javascript', src='script.js')

with doc:
    #with div(id='header').add(ol()):
        #for i in ['home', 'about', 'contact']:
            #li(a(i.title(), href='/%s.html' % i))

    with div(cls='row'):
        h1('education-counts-data')
        for sorx in sorted_x:
            a(dominate.tags.p(sorx[0]), href = sorx[1])
        #for fil in files:
            #gied = afi.text
            #gifz = gied.replace(' ', '-')
            #giflow = gifz.lower()
            #a(dominate.tags.p(fil), href = fil)

#print doc

Filter html to display only certain extensions. For example - xls.
or doc.
Render the filtered extension

In [ ]:
print doc

In [133]:
mkind = open(indfil, 'w')

In [139]:
for exf in exlfile:
    #print exf
    opexf = open(exf, 'r')
    #rdex = xlrd.count_records(exf)
    #rdwk = xlrd.open_workbook(opexf)
    #print rdwk
    pandexl = pandas.read_excel(exf)
    #print pandexl.columns
    pandex = pandexl.to_html()
    yourstring = pandex.encode('ascii', 'ignore').decode('ascii')

    mkind.write(str(yourstring))

mkind.close()

In [ ]:
document = Document('existing-document-file.docx')
document.save('new-file-name.docx')

In [ ]:
for docf in docfiles:
    #print docf
    print docf
    docum = Document(docf)

In [ ]:

document = Document()

In [ ]:
document.